# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e08927251f42106ca0eac5235f81a4675bbc80dc8bc6143ff740f9424443230f1fd258ccb9cbad2be144e95b62d5fc1559a7f61a4c5346de5acd0bf7fb605e8

test:
  secret_key_base: 405fa36024fc2e9a93e90daa4cb481e34ae02fe3b75cfbbaaed885a0b152f5389f67fbe230f708dc352215da0e7fd419f3dfaed578193665471033218b05b8ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
